# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MMS-ProviderMailParser-UKVodafone
version:      0.02
version_from: lib/MMS/ProviderMailParser/UKVodafone.pm
installdirs:  site
requires:
    HTML::TableExtract:            0
    MMS::MailMessage::ProviderParsed: 0.02
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
